-- ============================================================================
-- 011 — Equipment Authority from lab_equipment_seed_v1.json (David, Drive)
-- GENERATED by scripts/gen_canonical_seeds.mjs — do not edit by hand.
-- The missing identity layer: instruments + the property codes they measure +
-- standards. Equipment is the "how measured" parameter of an axis.
-- ============================================================================
CREATE TABLE IF NOT EXISTS equipment (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT UNIQUE NOT NULL,
  type        TEXT,
  measures    JSONB NOT NULL DEFAULT '[]',   -- property codebook codes this instrument measures
  standards   JSONB NOT NULL DEFAULT '[]',   -- ASTM/ISO/EN standards supported
  status      TEXT,                          -- 'existing' = owned & active
  projects    JSONB NOT NULL DEFAULT '[]',
  created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS equipment_measures_idx ON equipment USING GIN (measures);

INSERT INTO equipment (name,type,measures,standards,status,projects) VALUES
  ('Pushen NDJ-5S','rotational viscometer','["VISC_WET","THIXO_INDEX"]'::jsonb,'["ASTM D2196","ISO 2555"]'::jsonb,'existing','["all coatings"]'::jsonb),
  ('SNB-3 Viscometer','rotational viscometer','["VISC_WET","THIXO_INDEX"]'::jsonb,'["ASTM D2196","ISO 2555"]'::jsonb,'existing','[]'::jsonb),
  ('LANGRY LR-P40','pull-off adhesion tester','["ADHES_DRY"]'::jsonb,'["ASTM D4541","ASTM D7234","ASTM D7334","EN 1542","ISO 4624","ISO 19403"]'::jsonb,'existing','["PR-TFX","ERL-01"]'::jsonb),
  ('BGD 502/5A','cross-hatch cutter','["ADHES_DRY","FLEX_DRY"]'::jsonb,'["ASTM D3359","ISO 2409","EN ISO 2409"]'::jsonb,'existing','[]'::jsonb),
  ('CM-8826FN (Biuged)','gloss meter 60deg','["GLOSS"]'::jsonb,'["ASTM D523","ISO 2813"]'::jsonb,'existing','[]'::jsonb),
  ('HOBERSAL Muffle Furnace','muffle / calcination furnace 600-1000C','["FIRE_DRY","EXPANSION","CHAR_QUAL"]'::jsonb,'["ASTM D2863","ASTM E1354","ASTM E84","ISO 1182","ISO 1716"]'::jsonb,'existing','["INT-TFX (critical)"]'::jsonb),
  ('Building Materials Flammability Furnace','flammability / flame-spread test','["FIRE_DRY"]'::jsonb,'["ASTM E84","EN 13501-1","ISO 11925-2"]'::jsonb,'existing','["INT-TFX (critical)"]'::jsonb),
  ('HU04-10 Salt Spray Chamber','salt-spray / corrosion chamber','["WATERRES_DRY"]'::jsonb,'["ASTM B117","ISO 9227"]'::jsonb,'existing','["PR-TFX (critical)"]'::jsonb),
  ('SS-301 Sieve Shaker','sieve shaker (particle size)','["PACKING"]'::jsonb,'["ASTM C136","ASTM C430","EN 933","ISO 3310"]'::jsonb,'existing','["CSC-01 (critical)"]'::jsonb),
  ('TQC VF2200-666 / VF2201-589','water-vapor permeability cups (Payne/Wet-cup)','["BREATH"]'::jsonb,'["EN ISO 7783","ASTM E96"]'::jsonb,'existing','[]'::jsonb),
  ('BGD wet-film / Taber abrasion (Biuged)','abrasion + wet-film','["SCRUB","SAG_WET","BUILD"]'::jsonb,'["ASTM D4060","ASTM D4414"]'::jsonb,'existing','[]'::jsonb),
  ('BGD 542/S','coating thickness gauge','["BUILD"]'::jsonb,'["ASTM D7091","ISO 2178","ISO 2360","ISO 2808"]'::jsonb,'existing','[]'::jsonb),
  ('Density Cup VF2039-1015 / Pycnometer','density / pycnometer cup','["PVC","COST"]'::jsonb,'["ASTM D1475","ISO 2811","EN ISO 2811"]'::jsonb,'existing','[]'::jsonb),
  ('Color spectro (LR-P40 suite)','colorimeter / spectro','["OPACITY","UV_DRY"]'::jsonb,'["ASTM D2244","ASTM E308","ISO 7724","ISO 11664"]'::jsonb,'existing','[]'::jsonb),
  ('EUTECH pH 700','pH meter','[]'::jsonb,'["ASTM C25","ISO 10523"]'::jsonb,'existing','["CSC-01 (critical)"]'::jsonb),
  ('SNOL MSF 11-3/8','drying / heating oven <=300C','["SET_TIME"]'::jsonb,'["ASTM C109","ASTM D1640","EN 196","ISO 3270"]'::jsonb,'existing','[]'::jsonb),
  ('GFL 70','forced-air drying oven','[]'::jsonb,'["ASTM C109","ASTM D823","ASTM D1640"]'::jsonb,'existing','[]'::jsonb),
  ('RADWAG PS 1000.R1','analytical balance','[]'::jsonb,'[]'::jsonb,'existing','[]'::jsonb),
  ('R Technology YP50002','precision balance / penetrometer','[]'::jsonb,'["ASTM C305","ASTM D823"]'::jsonb,'existing','[]'::jsonb),
  ('MRC RC-1000','overhead stirrer','[]'::jsonb,'["ASTM C305","ISO 1514"]'::jsonb,'existing','[]'::jsonb),
  ('High-Shear Disperser / Cowles','high-shear disperser','[]'::jsonb,'["ASTM D4761"]'::jsonb,'existing','["PR-TFX (critical)"]'::jsonb),
  ('GOTECH (cement press)','compression / cement strength','["HARD_DRY"]'::jsonb,'["ASTM C109","ASTM C39","EN 196-1","ISO 679"]'::jsonb,'existing','["CSC-01 (critical)"]'::jsonb),
  ('Schmidt Rebound Hammer HT225-N / HT75-L','rebound hammer (surface hardness)','["HARD_DRY"]'::jsonb,'["ASTM C805","EN 12504-2"]'::jsonb,'existing','[]'::jsonb),
  ('Tesla Planetary Mixer','planetary mixer','[]'::jsonb,'["ASTM D1210","ISO 1524","ISO 2431","ISO 3251"]'::jsonb,'existing','[]'::jsonb),
  ('TOCSIN-640 (IGD)','fixed gas detector (safety)','[]'::jsonb,'["EN 45544","EN 60079"]'::jsonb,'existing','[]'::jsonb)
ON CONFLICT (name) DO NOTHING;
