import fs from 'fs';
import path from 'path';
const here = path.dirname(new URL(import.meta.url).pathname);
const prop = JSON.parse(fs.readFileSync(path.resolve(here, '../config/property_registry_canonical_v1.json'), 'utf8'));
const equip = JSON.parse(fs.readFileSync(path.resolve(here, '../config/lab_equipment_seed_v1.json'), 'utf8'));
const esc = s => String(s).replace(/'/g, "''");
const j = o => esc(JSON.stringify(o));

// --- 010: canonical axes from the property registry ---
const axisRows = prop.properties.map(p =>
  `  ('${esc(p.property_id)}','${esc(p.name)}','${esc(p.property_id)}','${esc(p.unit)}','${esc(p.method)}',TRUE,'${j(p.aliases||[])}'::jsonb,'${esc(p.direction_of_good)}','${esc(p.evidence_tier)}',${p.method_alias?`'${esc(p.method_alias)}'`:'NULL'},${p.codebook?`'${esc(p.codebook)}'`:'NULL'})`
).join(',\n');
const m010 = `-- ============================================================================
-- 010 — Canonical axes from property_registry_canonical_v1.json (David, Drive)
-- GENERATED by scripts/gen_canonical_seeds.mjs — do not edit by hand.
-- Registry status: DRAFT / HUMAN_REVIEW / NOT_DEPLOYED. Additive; run after review.
-- Supersedes the hand axis seeds in 007/008 (snake_case canonical ids per D6):
--   EXPANSION->expansion_ratio, TIME_TO_FAILURE->time_to_failure,
--   CHAR_DENSITY/CHAR_HEIGHT->char_quality+density, ADHESION->pull_off_adhesion.
-- ============================================================================
ALTER TABLE axes ADD COLUMN IF NOT EXISTS direction_of_good TEXT;
ALTER TABLE axes ADD COLUMN IF NOT EXISTS evidence_tier TEXT;
ALTER TABLE axes ADD COLUMN IF NOT EXISTS method_alias TEXT;
ALTER TABLE axes ADD COLUMN IF NOT EXISTS codebook TEXT;

INSERT INTO axes (axis_id,name,dimension,canonical_unit,method,is_scalar,aliases,direction_of_good,evidence_tier,method_alias,codebook) VALUES
${axisRows}
ON CONFLICT (axis_id) DO NOTHING;
`;
fs.writeFileSync(path.resolve(here, '../migrations/010_axes_canonical.sql'), m010);

// --- 011: equipment table + seed ---
const eqRows = equip.equipment.map(e =>
  `  ('${esc(e.name)}','${esc(e.type)}','${j(e.measures||[])}'::jsonb,'${j(e.standards||[])}'::jsonb,'${esc(e.status)}','${j(e.projects||[])}'::jsonb)`
).join(',\n');
const m011 = `-- ============================================================================
-- 011 — Equipment Authority from lab_equipment_seed_v1.json (David, Drive)
-- GENERATED by scripts/gen_canonical_seeds.mjs — do not edit by hand.
-- The missing identity layer: instruments + the property codes they measure +
-- standards. Equipment is the "how measured" parameter of an axis.
-- ============================================================================
CREATE TABLE IF NOT EXISTS equipment (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT UNIQUE NOT NULL,
  type        TEXT,
  measures    JSONB NOT NULL DEFAULT '[]',   -- property codebook codes this instrument measures
  standards   JSONB NOT NULL DEFAULT '[]',   -- ASTM/ISO/EN standards supported
  status      TEXT,                          -- 'existing' = owned & active
  projects    JSONB NOT NULL DEFAULT '[]',
  created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS equipment_measures_idx ON equipment USING GIN (measures);

INSERT INTO equipment (name,type,measures,standards,status,projects) VALUES
${eqRows}
ON CONFLICT (name) DO NOTHING;
`;
fs.writeFileSync(path.resolve(here, '../migrations/011_equipment.sql'), m011);
console.log('generated migrations 010 (', prop.properties.length, 'axes ) and 011 (', equip.equipment.length, 'instruments )');
